<?php

acf_add_local_field_group(array (
  'key' => 'group_58da7eafc06b6',
  'title' => '330 - Simulator/Solution Categories (2-column)',
  'fields' => array (
    array (
      'key' => 'field_58dfd575549e5',
      'label' => 'Simulator/Solutions',
      'name' => 'simulator-solutions_2up',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'categories-2up',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Add Category',
      'sub_fields' => array (
        array (
          'key' => 'field_58dfd9f533792',
          'label' => 'Simulator/Solution Name',
          'name' => 'category-2up_name',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => 'categories-2up categories-2up__name',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58dfdba733793',
          'label' => 'Category Type',
          'name' => 'category-2up_simulator-solution',
          'type' => 'select',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '25',
            'class' => 'categories-2up categories-2up__type',
            'id' => '',
          ),
          'choices' => array (
            'simulator: Simulator' => 'simulator: Simulator',
            'solution: Solution' => 'solution: Solution',
          ),
          'default_value' => array (
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'ajax' => 0,
          'return_format' => 'label',
          'placeholder' => '',
        ),
        array (
          'key' => 'field_58dfdc2f33794',
          'label' => 'Icon',
          'name' => 'category-2up_icon',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '25',
            'class' => 'categories-2up categories-2up__type',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58dfdc8333795',
          'label' => 'Category Page',
          'name' => 'category-2up_page',
          'type' => 'page_link',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '30',
            'class' => 'categories-2up categories-2up__page',
            'id' => '',
          ),
          'post_type' => array (
          ),
          'taxonomy' => array (
          ),
          'allow_null' => 0,
          'allow_archives' => 1,
          'multiple' => 0,
        ),
        array (
          'key' => 'field_58dfdce533796',
          'label' => 'Excerpt',
          'name' => 'category-2up_excerpt',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '70',
            'class' => 'categories-2up categories-2up__excerpt',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => 'full',
          'media_upload' => 0,
          'delay' => 0,
        ),
        array (
          'key' => 'field_58dff323b5173',
          'label' => 'Background Override',
          'name' => 'category-2up_override',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '30',
            'class' => 'categories-2up categories-2up__override',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 0,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
        array (
          'key' => 'field_58dff415b5174',
          'label' => 'Background Image',
          'name' => 'category-2up_background',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dff323b5173',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '70',
            'class' => 'categories-2up categories-2up__override',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'medium',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 0,
  'description' => '',
));

?>