<?php

acf_add_local_field_group(array (
  'key' => 'group_58d0223c875e6',
  'title' => 'Features',
  'fields' => array (

    //Global Settings
    array (
      'key' => 'field_58e7b13526844',
      'label' => 'Global Settings',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58e7b862e8aa7',
      'label' => 'Brand Logo',
      'name' => 'global_brandLogo',
      'type' => 'image',
      'instructions' => 'The logo associated with the FAAC brand, for use throughout the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7b99de8aa8',
      'label' => 'Menu Logo',
      'name' => 'global_menuLogo',
      'type' => 'image',
      'instructions' => 'The logo, as it should appear in the primary navigation menu at the top of the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7ba31e8aa9',
      'label' => 'Footer Logo',
      'name' => 'global_footerLogo',
      'type' => 'image',
      'instructions' => 'The logo as it should appear in the page footer masthead.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),

    // Call to Action Defaults
    array (
      'key' => 'field_58d023c238525',
      'label' => 'Calls to Action',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58d0491b4754d',
      'label' => 'Tagline',
      'name' => 'cta_tagline',
      'type' => 'text',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '100',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d0498c4754e',
      'label' => 'Phone Number',
      'name' => 'cta_phone',
      'type' => 'text',
      'instructions' => 'Please enter a value in the format XXX-XXX-XXXX.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '40',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d049c34754f',
      'label' => 'Photo',
      'name' => 'cta_photo',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '60',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'full',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),

    // Photo Promotion Defaults
    array (
      'key' => 'field_58d0236f38523',
      'label' => 'Photo Promotion',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58d046a8f864a',
      'label' => 'Headline',
      'name' => 'photoPromotion_headline',
      'type' => 'text',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '100',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d046d9f864b',
      'label' => 'Excerpt',
      'name' => 'photoPromotion_excerpt',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '60',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'basic',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58d04754f864c',
      'label' => 'Image',
      'name' => 'photoPromotion_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '40',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'full',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),

    // Video Promotion Defaults
    array (
      'key' => 'field_58d0233238521',
      'label' => 'Video Promotion',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 1,
    ),
    array (
      'key' => 'field_58d043dce484c',
      'label' => 'Headline',
      'name' => 'videoPromotion_headline',
      'type' => 'text',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '100',
        'class' => 'faac-video-promotion__headline',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d044fee484e',
      'label' => 'Excerpt',
      'name' => 'videoPromotion_excerpt',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '60',
        'class' => 'faac-video-promotion__url',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'basic',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58d0449ce484d',
      'label' => 'Video URL',
      'name' => 'videoPromotion_url',
      'type' => 'oembed',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '40',
        'class' => 'faac-video-promotion__url',
        'id' => '',
      ),
      'width' => '',
      'height' => '',
    ),

    // Footer Link Defaults
    array (
      'key' => 'field_58d023c838526',
      'label' => 'Footer Promotions',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58d04d79c9eba',
      'label' => 'Latest News',
      'name' => 'footerPromotions_news',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '25',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'post',
        1 => 'page',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
    ),
    array (
      'key' => 'field_58d04ea1ad068',
      'label' => 'Resources',
      'name' => 'footerPromotions_resources',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '25',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'post',
        1 => 'page',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
    ),
    array (
      'key' => 'field_58d04eb4ad069',
      'label' => 'Careers',
      'name' => 'footerPromotions_careers',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '25',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'post',
        1 => 'page',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-features',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>