<?php

acf_add_local_field_group(array (
  'key' => 'group_58d02e4322867',
  'title' => 'Testimonials',
  'fields' => array (
    array (
      'key' => 'field_58d02e73bd62a',
      'label' => '',
      'name' => 'faac_testimonials',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '100',
        'class' => 'faac-testimonial',
        'id' => '',
      ),
      'collapsed' => 'field_58d02fc54794e',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Add Testimonial',
      'sub_fields' => array (
        array (
          'key' => 'field_58d02fc54794e',
          'label' => 'Author',
          'name' => 'faac_testimonial_author',
          'type' => 'text',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => 'faac-testimonial__author',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58d034e8421a0',
          'label' => 'Organization',
          'name' => 'faac_testimonial_organization',
          'type' => 'text',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => 'faac-testimonial__organization',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58d03539421a1',
          'label' => 'Logo',
          'name' => 'faac_testimonial_logo',
          'type' => 'image',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '20',
            'class' => 'faac-testimonial__logo',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'full',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58d035c3421a3',
          'label' => 'Testimonial',
          'name' => 'faac_testimonial_text',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => 'faac-testimonial__text',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => 'basic',
          'media_upload' => 0,
          'delay' => 0,
        ),
        array (
          'key' => 'field_58d03573421a2',
          'label' => 'Background',
          'name' => 'faac_testimonial_background',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '30',
            'class' => 'faac-testimonial__background',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'full',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'faac-testimonials',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>