<?php

acf_add_local_field_group(array (
  'key' => 'group_58d98e5b9e0f1',
  'title' => '230 - Feature Block',
  'fields' => array (
    array (
      'key' => 'field_58daae63ca03e',
      'label' => 'Feature Blocks',
      'name' => 'feature-block',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'feature-block',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Add Feature Block',
      'sub_fields' => array (
        array (
          'key' => 'field_58daaeb7ca03f',
          'label' => 'Feature Direction',
          'name' => 'feature-block_direction',
          'type' => 'select',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '20',
            'class' => 'feature-block feature-block__direction',
            'id' => '',
          ),
          'choices' => array (
            'ltr' => 'Left to Right',
            'rtl' => 'RIght to Left',
          ),
          'default_value' => array (
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'ajax' => 0,
          'return_format' => 'value',
          'placeholder' => '',
        ),
        array (
          'key' => 'field_58dab122ca040',
          'label' => 'Photo',
          'name' => 'feature-block_photo_ltr',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58daaeb7ca03f',
                'operator' => '==',
                'value' => 'ltr',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '30',
            'class' => 'feature-block feature-block__photo feature-block__photo--ltr',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'medium',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58dab20311efd',
          'label' => 'Photo',
          'name' => 'feature-block_photo_rtl',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58daaeb7ca03f',
                'operator' => '==',
                'value' => 'rtl',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '30',
            'class' => 'feature-block feature-block__photo feature-block__photo--rtl',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'medium',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58dac6d549920',
          'label' => 'Title',
          'name' => 'feature-block_title_ltr',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58daaeb7ca03f',
                'operator' => '==',
                'value' => 'ltr',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '50',
            'class' => 'feature-block feature-block__title feature-block__title--ltr',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58dac70849921',
          'label' => 'Title',
          'name' => 'feature-block_title_rtl',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58daaeb7ca03f',
                'operator' => '==',
                'value' => 'rtl',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '50',
            'class' => 'feature-block feature-block__title feature-block__title--rtl',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58dab25111efe',
          'label' => 'Content',
          'name' => 'feature-block_content_ltr',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58daaeb7ca03f',
                'operator' => '==',
                'value' => 'ltr',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '',
            'class' => 'feature-block feature-block__content feature-block__content--ltr',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => 'full',
          'media_upload' => 0,
          'delay' => 0,
        ),
        array (
          'key' => 'field_58dab2af11eff',
          'label' => 'Content',
          'name' => 'feature-block_content_rtl',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58daaeb7ca03f',
                'operator' => '==',
                'value' => 'rtl',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '',
            'class' => 'feature-block feature-block__content feature-block__content--rtl',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => 'full',
          'media_upload' => 0,
          'delay' => 0,
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 0,
  'description' => '',
));

?>