<?php

acf_add_local_field_group(array (
  'key' => 'group_58eadccc1b1d2',
  'title' => 'Theme Settings - Call to Action',
  'fields' => array (
    array (
      'key' => 'field_58eb8a8937378',
      'label' => 'Tagline',
      'name' => 'cta_tagline',
      'type' => 'text',
      'instructions' => 'The primary text that drives the call-to-action message',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Ready for High Fidelity Training?',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb8b7c37379',
      'label' => 'Button Text',
      'name' => 'cta_buttonText',
      'type' => 'text',
      'instructions' => 'The text on the cta button',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Speak to a Specialist',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb8ba73737a',
      'label' => 'Phone Number',
      'name' => 'cta_phoneNumber',
      'type' => 'text',
      'instructions' => 'The phone number to include as an alternate contact method.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => 'XXX-XXX-XXXX',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb8bdf3737b',
      'label' => 'Background Image',
      'name' => 'cta_background',
      'type' => 'image',
      'instructions' => 'The graphic to use as a graphic behind the cta content',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-calls-to-action',
      ),
    ),
  ),
  'menu_order' => 11,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>