<?php

acf_add_local_field_group(array (
  'key' => 'group_58ead2b37407f',
  'title' => 'Theme Settings - Theme Defaults',
  'fields' => array (
    array (
      'key' => 'field_58ead2fdb3bc2',
      'label' => 'Brand Logo',
      'name' => 'faac_brandLogo',
      'type' => 'image',
      'instructions' => 'The logo associated with the brand as a whole.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58ead34d96bdd',
      'label' => 'Menu Logo',
      'name' => 'faac_menuLogo',
      'type' => 'image',
      'instructions' => 'The logo used in the primary navigation menu at the top of the page.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58ead39296bde',
      'label' => 'Footer Logo',
      'name' => 'faac_footerLogo',
      'type' => 'image',
      'instructions' => 'The logo used in the footer masthead.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-theme-defaults',
      ),
    ),
  ),
  'menu_order' => 10,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>