<?php

acf_add_local_field_group(array (
  'key' => 'group_58eb8db63711e',
  'title' => 'Theme Settings - Video Promotion',
  'fields' => array (
    array (
      'key' => 'field_58eb8db64b1f0',
      'label' => 'Linked Video',
      'name' => 'videoPromo_link',
      'type' => 'url',
      'instructions' => 'The source URL of the video',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_590367338651a',
      'label' => 'Video Thumbnail',
      'name' => 'videoPromo_thumbnail',
      'type' => 'image',
      'instructions' => 'Thumbnail image for the video',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_590367838651c',
      'label' => 'Video Headline',
      'name' => 'videoPromo_headline',
      'type' => 'text',
      'instructions' => 'Text to display, overlaying the video thumbnail',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-video-promotions',
      ),
    ),
  ),
  'menu_order' => 13,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>