<?php

acf_add_local_field_group(array (
  'key' => 'group_58d3f05fbacaf',
  'title' => '110 - Dynamic Slider',
  'fields' => array (
    array (
      'key' => 'field_58d3f05fbf1cf',
      'label' => 'Dynamic Slider',
      'name' => 'dynamic-slider',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '100',
        'class' => 'hero-slider',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Add Image',
      'sub_fields' => array (
        array (
          'key' => 'field_58d3f12231cab',
          'label' => 'Slide Image',
          'name' => 'dynamic-slider_image',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '20',
            'class' => 'dynamic-slider dynamic-slider__image',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58d3f16331cac',
          'label' => 'Upper Text',
          'name' => 'dynamic-slider_upper-text',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '40',
            'class' => 'dynamic-slider dynamic-slider__upper-text',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58d3f18531cad',
          'label' => 'Lower Text',
          'name' => 'dynamic-slider_lower-text',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '40',
            'class' => 'dynamic-slider dynamic-slider__lower-text',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'acf_after_title',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 0,
  'description' => '',
));

?>