<?php

acf_add_local_field_group(array (
  'key' => 'group_58da7ea1e866f',
  'title' => '300 - Category Heading',
  'fields' => array (
    array (
      'key' => 'field_58eceb12758aa',
      'label' => 'Heading',
      'name' => 'heading',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Heading',
      'sub_fields' => array (
        array (
          'key' => 'field_58ecec90758ac',
          'label' => 'Icon',
          'name' => 'heading_icon',
          'type' => 'select',
          'instructions' => 'If appropriate, the icon that appears on top of the text',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'military' => 'Military',
            'publicSafety' => 'Public Safety',
            'useOfForce' => 'Use of Force',
            'transportation' => 'Transportation',
            'research' => 'Research',
          ),
          'default_value' => array (
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'ajax' => 0,
          'return_format' => 'array',
          'placeholder' => '',
        ),
        array (
          'key' => 'field_58ecebf4758ab',
          'label' => 'Upper Text',
          'name' => 'heading_upperText',
          'type' => 'text',
          'instructions' => 'The text that appears above the solutions or simulators identifier',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58ececc9758ad',
          'label' => 'Category Select',
          'name' => 'heading_select',
          'type' => 'select',
          'instructions' => 'Is this heading for Simulators or Solutions?',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'simulators' => 'Simulators',
            'solutions' => 'Solutions',
          ),
          'default_value' => array (
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'ajax' => 0,
          'return_format' => 'array',
          'placeholder' => '',
        ),
        array (
          'key' => 'field_58fa4b60ba506',
          'label' => 'Link Status',
          'name' => 'heading_linkSelector',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'message' => 'Should this link to another page?',
          'default_value' => 0,
          'ui' => 0,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
        array (
          'key' => 'field_58fa4bd3ba507',
          'label' => 'Linked Page',
          'name' => 'heading_linkedPage',
          'type' => 'page_link',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58fa4b60ba506',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array (
            0 => 'page',
          ),
          'taxonomy' => array (
          ),
          'allow_null' => 0,
          'allow_archives' => 1,
          'multiple' => 0,
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
  ),
  'active' => 0,
  'description' => '',
));

?>