<?php

acf_add_local_field_group(array (
  'key' => 'group_58d31322a60eb',
  'title' => '100 - Basic Slider',
  'fields' => array (
    array (
      'key' => 'field_58d31322abce2',
      'label' => 'Slides',
      'name' => 'slider_gallery',
      'type' => 'gallery',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '60',
        'class' => '',
        'id' => '',
      ),
      'min' => '',
      'max' => '',
      'insert' => 'append',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58d31385dcce8',
      'label' => 'Slider Category (optional)',
      'name' => 'slider_category',
      'type' => 'select',
      'instructions' => 'Defines the icon to be displayed with the slider',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '40',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'none' => 'None',
        'military' => 'Military',
        'useOfForce' => 'Use of Force',
        'publicSafety' => 'Public Safety',
        'transportation' => 'Transportation',
        'research' => 'Research',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'array',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58d31322abc85',
      'label' => 'Upper Text',
      'name' => 'slider_upperText',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d31322abcb4',
      'label' => 'Lower Text',
      'name' => 'slider_lowerText',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => 'basic-slider basic-slider__lower-text',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'acf_after_title',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 0,
  'description' => '',
));

?>