<?php

acf_add_local_field_group(array (
  'key' => 'group_58da8160620c4',
  'title' => '590 - Promotion Links',
  'fields' => array (
    array (
      'key' => 'field_58e28c7acb8ad',
      'label' => 'News Override',
      'name' => 'promo-links_news_override',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '33',
        'class' => 'promo-links promo-links__override',
        'id' => '',
      ),
      'message' => 'Custom news link?',
      'default_value' => 0,
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array (
      'key' => 'field_58e28cf5cb8ae',
      'label' => 'Resources Override',
      'name' => 'promo-links_resources_override',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '33',
        'class' => 'promo-links promo-links__override',
        'id' => '',
      ),
      'message' => 'Custom resources link?',
      'default_value' => 0,
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array (
      'key' => 'field_58e28cf7cb8af',
      'label' => 'Careers Override',
      'name' => 'promo-links_careers_override',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '33',
        'class' => 'promo-links promo-links__override',
        'id' => '',
      ),
      'message' => 'Custom news link?',
      'default_value' => 0,
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array (
      'key' => 'field_58e28d35cb8b0',
      'label' => 'Latest News Page',
      'name' => 'promo-links_news_page',
      'type' => 'page_link',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28c7acb8ad',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__page',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58e28dfacb8b3',
      'label' => 'Latest News Headline',
      'name' => 'promo-links_news_headline',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28c7acb8ad',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__headline',
        'id' => '',
      ),
      'default_value' => 'Latest News',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58e28e29cb8b4',
      'label' => 'Latest News Excerpt',
      'name' => 'promo-links_news_excerpt',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28c7acb8ad',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__excerpt',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58e28e5ccb8b5',
      'label' => 'Latest News Photo',
      'name' => 'promo-links_news_photo',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28c7acb8ad',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__photo',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'medium',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e28e9dcb8b9',
      'label' => 'Resources Page',
      'name' => 'promo-links_resources_page',
      'type' => 'page_link',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28cf5cb8ae',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__page',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58e28e85cb8b6',
      'label' => 'Resources Headline',
      'name' => 'promo-links_resources_headline',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28cf5cb8ae',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__headline',
        'id' => '',
      ),
      'default_value' => 'Resources',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58e28e89cb8b7',
      'label' => 'Resources Excerpt',
      'name' => 'promo-links_resources_excerpt',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28cf5cb8ae',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__excerpt',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58e28e8bcb8b8',
      'label' => 'Resources Photo',
      'name' => 'promo-links_resources_photo',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28cf5cb8ae',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__photo',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'medium',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e28ebccb8ba',
      'label' => 'Careers Page',
      'name' => 'promo-links_careers_page',
      'type' => 'page_link',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28cf7cb8af',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__page',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58e28ec1cb8bb',
      'label' => 'Careers Headline',
      'name' => 'promo-links_careers_headline',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28cf7cb8af',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__headline',
        'id' => '',
      ),
      'default_value' => 'Careers',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58e28ec3cb8bc',
      'label' => 'Careers Excerpt',
      'name' => 'promo-links_careers_excerpt',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28cf7cb8af',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__excerpt',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58e28ec6cb8bd',
      'label' => 'Careers Photo',
      'name' => 'promo-links_careers_photo',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58e28cf7cb8af',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '50',
        'class' => 'promo-links promo-links__photo',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'medium',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 0,
  'description' => '',
));

?>