<?php

acf_add_local_field_group(array (
  'key' => 'group_58da7ea1e866f',
  'title' => '300 - Category Heading',
  'fields' => array (
    array (
      'key' => 'field_58eceb12758aa',
      'label' => 'Heading',
      'name' => 'heading',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Heading',
      'sub_fields' => array (
        array (
          'key' => 'field_58ecec90758ac',
          'label' => 'Icon',
          'name' => 'heading_icon',
          'type' => 'select',
          'instructions' => 'If appropriate, the icon that appears on top of the text',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '100',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'none' => 'None',
            'faacCommercial' => 'FAAC Commercial',
            'faacMilitary' => 'FAAC Military',
            'miloRange' => 'Milo Range',
            'rti' => 'Realtime Technologies (RTI)',
            'custom' => 'Custom',
          ),
          'default_value' => array (
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'ajax' => 0,
          'return_format' => 'array',
          'placeholder' => '',
        ),
        array (
          'key' => 'field_58f106831a1d3',
          'label' => 'Custom Icon',
          'name' => 'heading_customIcon',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58ecec90758ac',
                'operator' => '==',
                'value' => 'custom',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '100',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58ecebf4758ab',
          'label' => 'Upper Text',
          'name' => 'heading_upperText',
          'type' => 'text',
          'instructions' => 'The text that appears above the solutions or simulators identifier',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58ececc9758ad',
          'label' => 'Category Select',
          'name' => 'heading_select',
          'type' => 'select',
          'instructions' => 'Is this heading for Simulators or Solutions?',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'simulators' => 'Simulators',
            'solutions' => 'Solutions',
          ),
          'default_value' => array (
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'ajax' => 0,
          'return_format' => 'array',
          'placeholder' => '',
        ),
        array (
          'key' => 'field_58f106e81a1d4',
          'label' => 'Page Link',
          'name' => 'heading_pageLink',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'message' => 'Link heading to a page?',
          'default_value' => 0,
          'ui' => 0,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
        array (
          'key' => 'field_58f1072c1a1d5',
          'label' => 'Linked Page',
          'name' => 'heading_page',
          'type' => 'page_link',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array (
            0 => 'page',
          ),
          'taxonomy' => array (
          ),
          'allow_null' => 0,
          'allow_archives' => 1,
          'multiple' => 0,
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 0,
  'description' => '',
));

?>