<?php

acf_add_local_field_group(array (
  'key' => 'group_58da7ead4190d',
  'title' => '320 - Category Media Block',
  'fields' => array (
    array (
      'key' => 'field_58dfc6cad05f4',
      'label' => 'Category Block',
      'name' => 'category-block',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'category-block',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Add Category',
      'sub_fields' => array (
        array (
          'key' => 'field_58dfca52d05f7',
          'label' => 'Orientation',
          'name' => 'cateogry-block_orientation',
          'type' => 'select',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '60',
            'class' => 'category-block category-block__orientation',
            'id' => '',
          ),
          'choices' => array (
            'ltr' => 'Photo on left, content on right',
            'rtl' => 'Photo on right, content on left',
          ),
          'default_value' => array (
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'ajax' => 0,
          'return_format' => 'value',
          'placeholder' => '',
        ),
        array (
          'key' => 'field_58dfcba8d05f8',
          'label' => 'Feature Image',
          'name' => 'cateogry-block_feature-ltr',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'ltr',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '50',
            'class' => 'category-block category-block__feature--ltr',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'medium',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58dfce77d05f9',
          'label' => 'Category Title',
          'name' => 'cateogry-block_title-ltr',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'ltr',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '35',
            'class' => 'category-block category-block__title--ltr',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58dfcebdd05fa',
          'label' => 'Icon',
          'name' => 'cateogry-block_icon-ltr',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'ltr',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '15',
            'class' => 'category-block category-block__icon--ltr',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58dfcefcd05fb',
          'label' => 'Heading',
          'name' => 'cateogry-block_heading-ltr',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'ltr',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '30',
            'class' => 'category-block category-block__heading--ltr',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58dfcfc4d05fc',
          'label' => 'Description',
          'name' => 'cateogry-block_description-ltr',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'ltr',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '70',
            'class' => 'category-block category-block__description--ltr',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => 'full',
          'media_upload' => 0,
          'delay' => 0,
        ),
        array (
          'key' => 'field_58dfd13ad05fe',
          'label' => 'Solutions Page',
          'name' => 'cateogry-block_solutions-ltr',
          'type' => 'page_link',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'ltr',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '40',
            'class' => 'category-block category-block__solutions--ltr',
            'id' => '',
          ),
          'post_type' => array (
          ),
          'taxonomy' => array (
          ),
          'allow_null' => 0,
          'allow_archives' => 1,
          'multiple' => 0,
        ),
        array (
          'key' => 'field_58dfd180d05ff',
          'label' => 'Simulators Page',
          'name' => 'cateogry-block_simulators-ltr',
          'type' => 'page_link',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'ltr',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '40',
            'class' => 'category-block category-block__simulators--ltr',
            'id' => '',
          ),
          'post_type' => array (
          ),
          'taxonomy' => array (
          ),
          'allow_null' => 0,
          'allow_archives' => 1,
          'multiple' => 0,
        ),
        array (
          'key' => 'field_58dfd21270c8c',
          'label' => 'Icon',
          'name' => 'cateogry-block_icon-rtl',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'rtl',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '15',
            'class' => 'category-block category-block__icon--rtl',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58dfd1e670c8b',
          'label' => 'Category Title',
          'name' => 'cateogry-block_title-rtl',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'rtl',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '35',
            'class' => 'category-block category-block__title--rtl',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58dfd1b970c8a',
          'label' => 'Feature Image',
          'name' => 'cateogry-block_feature-rtl',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'rtl',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '50',
            'class' => 'category-block category-block__feature--rtl',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'medium',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58dfd24970c8d',
          'label' => 'Heading',
          'name' => 'cateogry-block_heading-rtl',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'rtl',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '30',
            'class' => 'category-block category-block__heading--rtl',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58dfd24c70c8e',
          'label' => 'Description',
          'name' => 'cateogry-block_description-rtl',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'rtl',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '70',
            'class' => 'category-block category-block__description--rtl',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => 'full',
          'media_upload' => 0,
          'delay' => 0,
        ),
        array (
          'key' => 'field_58dfd25370c90',
          'label' => 'Solutions Page',
          'name' => 'cateogry-block_solutions-rtl',
          'type' => 'page_link',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'rtl',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '40',
            'class' => 'category-block category-block__solutions--rtl',
            'id' => '',
          ),
          'post_type' => array (
          ),
          'taxonomy' => array (
          ),
          'allow_null' => 0,
          'allow_archives' => 1,
          'multiple' => 0,
        ),
        array (
          'key' => 'field_58dfd25670c91',
          'label' => 'Simulators Page',
          'name' => 'cateogry-block_simulators-rtl',
          'type' => 'page_link',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_58dfca52d05f7',
                'operator' => '==',
                'value' => 'rtl',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '40',
            'class' => 'category-block category-block__simulators--rtl',
            'id' => '',
          ),
          'post_type' => array (
          ),
          'taxonomy' => array (
          ),
          'allow_null' => 0,
          'allow_archives' => 1,
          'multiple' => 0,
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 0,
  'description' => '',
));

?>