<?php

acf_add_local_field_group(array (
  'key' => 'group_58da7eb6784b3',
  'title' => '360 - Featured Simulator/Solution',
  'fields' => array (
    array (
      'key' => 'field_58dac213fcf4d',
      'label' => 'Simulator',
      'name' => 'featured-simulator_page',
      'type' => 'page_link',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => 'featured-simulator featured-simulator__page',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 0,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58dac103fcf4b',
      'label' => 'Headline',
      'name' => 'featured-simulator_headline',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => 'featured-simulator featured-simulator__headline',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58dac1c4fcf4c',
      'label' => 'Description',
      'name' => 'featured-simulator_description',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'featured-simulator featured-simulator__headline',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58dac26dfcf4e',
      'label' => 'Override Checkbox',
      'name' => 'featured-simulator_override',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '15',
        'class' => 'featured-simulator featured-simulator__override',
        'id' => '',
      ),
      'message' => 'Use Different Photo?',
      'default_value' => 0,
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array (
      'key' => 'field_58dac35dfcf4f',
      'label' => 'Custom Photo',
      'name' => 'featured-simulator_custom-photo',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_58dac26dfcf4e',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '35',
        'class' => 'featured-simulator featured-simulator__photo',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'medium',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58dac3c6fcf50',
      'label' => 'Button Text',
      'name' => 'featured-simulator_button-text',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '25',
        'class' => 'featured-simulator featured-simulator__button',
        'id' => '',
      ),
      'default_value' => 'Get Started',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58dac40afcf51',
      'label' => 'Phone Number',
      'name' => 'featured-simulator_phone-number',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '25',
        'class' => 'featured-simulator featured-simulator__phone',
        'id' => '',
      ),
      'default_value' => '555-555-5555',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 0,
  'description' => '',
));

?>