<?php

acf_add_local_field_group(array (
  'key' => 'group_58e2a907a4cf7',
  'title' => 'Homepage (1)',
  'fields' => array (
    array (
      'key' => 'field_58e2a907a93c4',
      'label' => 'Slider',
      'name' => 'homepage_slider',
      'type' => 'clone',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'homepage homepage__slider',
        'id' => '',
      ),
      'clone' => array (
        0 => 'group_58d3f05fbacaf',
      ),
      'display' => 'group',
      'layout' => 'block',
      'prefix_label' => 0,
      'prefix_name' => 1,
    ),
    array (
      'key' => 'field_58e2a907a9400',
      'label' => 'Intro Content',
      'name' => 'homepage_intro',
      'type' => 'clone',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'homepage homepage__intro',
        'id' => '',
      ),
      'clone' => array (
        0 => 'group_58d32e8d672b3',
      ),
      'display' => 'group',
      'layout' => 'block',
      'prefix_label' => 0,
      'prefix_name' => 1,
    ),
    array (
      'key' => 'field_58e2aa8923f1d',
      'label' => 'Link Photos',
      'name' => 'homepage_link-photos',
      'type' => 'clone',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'homepage homepage__link-photos',
        'id' => '',
      ),
      'clone' => array (
        0 => 'group_58da7eaa88e52',
      ),
      'display' => 'group',
      'layout' => 'block',
      'prefix_label' => 0,
      'prefix_name' => 1,
    ),
    array (
      'key' => 'field_58e2abb423f1e',
      'label' => 'Solution / Simulator Categories',
      'name' => 'homepage_categories',
      'type' => 'clone',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'clone' => array (
        0 => 'group_58da7ead4190d',
      ),
      'display' => 'seamless',
      'layout' => 'block',
      'prefix_label' => 0,
      'prefix_name' => 0,
    ),
    array (
      'key' => 'field_58e2ac1723f1f',
      'label' => 'Division Intro',
      'name' => 'homepage_division',
      'type' => 'clone',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'homepage homepage__division-intro',
        'id' => '',
      ),
      'clone' => array (
        0 => 'group_58d32e8d672b3',
        1 => 'group_58d98e5159b2c',
      ),
      'display' => 'group',
      'layout' => 'block',
      'prefix_label' => 0,
      'prefix_name' => 1,
    ),
    array (
      'key' => 'field_58e2ac7f23f21',
      'label' => 'Footer Video Promotion',
      'name' => 'homepage_footer-video',
      'type' => 'clone',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'homepage homepage__footer-video',
        'id' => '',
      ),
      'clone' => array (
        0 => 'group_58da814fc3c5f',
      ),
      'display' => 'group',
      'layout' => 'block',
      'prefix_label' => 0,
      'prefix_name' => 1,
    ),
    array (
      'key' => 'field_58e2acbb23f22',
      'label' => 'Footer Photo Promotion',
      'name' => 'homepage_footer-photo',
      'type' => 'clone',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'homepage homepage__footer-video',
        'id' => '',
      ),
      'clone' => array (
        0 => 'group_58da814fc3c5f',
      ),
      'display' => 'group',
      'layout' => 'block',
      'prefix_label' => 0,
      'prefix_name' => 1,
    ),
    array (
      'key' => 'field_58e2acea23f23',
      'label' => 'Footer Links',
      'name' => 'homepage_footer-links',
      'type' => 'clone',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'homepage homepage__footer-links',
        'id' => '',
      ),
      'clone' => array (
        0 => 'group_58da8160620c4',
      ),
      'display' => 'group',
      'layout' => 'block',
      'prefix_label' => 0,
      'prefix_name' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_type',
        'operator' => '==',
        'value' => 'front_page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
  ),
  'active' => 1,
  'description' => '',
));

?>