<?php

// Global Settings options page
acf_add_local_field_group(array (
  'key' => 'group_58eaee2d324b4',
  'title' => 'Global Settings',
  'fields' => array (
    array (
      'key' => 'field_58eb983db4a8f',
      'label' => 'Simulators',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb985fb4a91',
      'label' => 'Featured Simulator',
      'name' => 'simulator_featuredPage',
      'type' => 'page_link',
      'instructions' => 'The simulator featured by default throughout the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb98b8b4a92',
      'label' => 'Link List Background Image',
      'name' => 'simulator_linkBackground',
      'type' => 'image',
      'instructions' => 'The background image to use for link lists (e.g. "Related Links")',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb98fcb4a93',
      'label' => 'Category Heading Background Image',
      'name' => 'simulator_headingBackground',
      'type' => 'image',
      'instructions' => 'The background image to use for category heading blocks',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb984cb4a90',
      'label' => 'Solutions',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb99356141e',
      'label' => 'Featured Solution',
      'name' => 'solution_featuredPage',
      'type' => 'page_link',
      'instructions' => 'The solution featured by default throughout the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb99346141d',
      'label' => 'Link List Background Image',
      'name' => 'solution_linkBackground',
      'type' => 'image',
      'instructions' => 'The background image to use for link lists (e.g. "Related Links")',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb99336141c',
      'label' => 'Category Heading Background Image',
      'name' => 'solution_headingBackground',
      'type' => 'image',
      'instructions' => 'The background image to use for category heading blocks',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-global-settings',
      ),
    ),
  ),
  'menu_order' => 30,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));




// Military options page
acf_add_local_field_group(array (
  'key' => 'group_58eaeea699a06',
  'title' => 'Military',
  'fields' => array (
    array (
      'key' => 'field_58eb99afaf201',
      'label' => 'General Settings',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb99c9af204',
      'label' => 'Display Name',
      'name' => 'military_name',
      'type' => 'text',
      'instructions' => 'The name of the category as it appears throughout the site',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Military',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb99eeaf205',
      'label' => 'Category Icon',
      'name' => 'military_icon',
      'type' => 'image',
      'instructions' => 'The primary icon used to represent the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9a50af206',
      'label' => 'Category Description',
      'name' => 'military_description',
      'type' => 'wysiwyg',
      'instructions' => 'A short description of the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58eb99b8af202',
      'label' => 'Simulators',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9a80ab9a6',
      'label' => 'Homepage',
      'name' => 'militarySimulator_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category simulators',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9acdab9a7',
      'label' => 'Heading Background',
      'name' => 'militarySimulator_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category simulator headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9b10ab9a8',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'militarySimulator_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9b90ab9a9',
      'label' => 'Link List Background',
      'name' => 'militarySimulator_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb99c2af203',
      'label' => 'Solutions',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9d8eab9ad',
      'label' => 'Homepage',
      'name' => 'militarySolution_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category solutions',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9d8eab9ac',
      'label' => 'Heading Background',
      'name' => 'militarySolution_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category solution headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9d8dab9ab',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'militarySolution_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9d8cab9aa',
      'label' => 'Link List Background',
      'name' => 'militarySolution_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-military',
      ),
    ),
  ),
  'menu_order' => 31,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));




// Use of Force options page
acf_add_local_field_group(array (
  'key' => 'group_58eb9e019bb58',
  'title' => 'Use of Force',
  'fields' => array (
    array (
      'key' => 'field_58eb9e01acc79',
      'label' => 'General Settings',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e01acd1c',
      'label' => 'Display Name',
      'name' => 'useOfForce_name',
      'type' => 'text',
      'instructions' => 'The name of the category as it appears throughout the site',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Use of Force',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb9e01acd87',
      'label' => 'Category Icon',
      'name' => 'useOfForce_icon',
      'type' => 'image',
      'instructions' => 'The primary icon used to represent the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e01ace23',
      'label' => 'Category Description',
      'name' => 'useOfForce_description',
      'type' => 'wysiwyg',
      'instructions' => 'A short description of the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58eb9e01aced2',
      'label' => 'Simulators',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e01acf39',
      'label' => 'Homepage',
      'name' => 'useOfForceSimulator_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category simulators',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9e01acfd5',
      'label' => 'Heading Background',
      'name' => 'useOfForceSimulator_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category simulator headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e01ad071',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'useOfForceSimulator_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e01ad0d7',
      'label' => 'Link List Background',
      'name' => 'useOfForceSimulator_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e01ad186',
      'label' => 'Solutions',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e01ad1ef',
      'label' => 'Homepage',
      'name' => 'useOfForceSolution_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category solutions',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9e01ad28b',
      'label' => 'Heading Background',
      'name' => 'useOfForceSolution_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category solution headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e01ad328',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'useOfForceSolution_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e01ad3a2',
      'label' => 'Link List Background',
      'name' => 'useOfForceSolution_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-use-of-force',
      ),
    ),
  ),
  'menu_order' => 32,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));




// Public Safety options page
acf_add_local_field_group(array (
  'key' => 'group_58eb9e08ce2a2',
  'title' => 'Public Safety',
  'fields' => array (
    array (
      'key' => 'field_58eb9e08e07b2',
      'label' => 'General Settings',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e08e07e7',
      'label' => 'Display Name',
      'name' => 'publicSafety_name',
      'type' => 'text',
      'instructions' => 'The name of the category as it appears throughout the site',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Military',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb9e08e0818',
      'label' => 'Category Icon',
      'name' => 'publicSafety_icon',
      'type' => 'image',
      'instructions' => 'The primary icon used to represent the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e08e0847',
      'label' => 'Category Description',
      'name' => 'publicSafety_description',
      'type' => 'wysiwyg',
      'instructions' => 'A short description of the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58eb9e08e0875',
      'label' => 'Simulators',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e08e08a4',
      'label' => 'Homepage',
      'name' => 'publicSafetySimulator_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category simulators',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9e08e0922',
      'label' => 'Heading Background',
      'name' => 'publicSafetySimulator_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category simulator headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e08e098a',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'publicSafetySimulator_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e08e0a28',
      'label' => 'Link List Background',
      'name' => 'publicSafetySimulator_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e08e0ac4',
      'label' => 'Solutions',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e08e0b33',
      'label' => 'Homepage',
      'name' => 'publicSafetySolution_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category solutions',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9e08e0c1c',
      'label' => 'Heading Background',
      'name' => 'publicSafetySolution_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category solution headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e08e0cb9',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'publicSafetySolution_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e08e0d54',
      'label' => 'Link List Background',
      'name' => 'publicSafetySolution_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-public-safety',
      ),
    ),
  ),
  'menu_order' => 33,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));




// Transportation options page
acf_add_local_field_group(array (
  'key' => 'group_58eb9e0c6cc7d',
  'title' => 'Transportation',
  'fields' => array (
    array (
      'key' => 'field_58eb9e0c806f7',
      'label' => 'General Settings',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c80735',
      'label' => 'Display Name',
      'name' => 'transportation_name',
      'type' => 'text',
      'instructions' => 'The name of the category as it appears throughout the site',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Military',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80768',
      'label' => 'Category Icon',
      'name' => 'transportation_icon',
      'type' => 'image',
      'instructions' => 'The primary icon used to represent the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80799',
      'label' => 'Category Description',
      'name' => 'transportation_description',
      'type' => 'wysiwyg',
      'instructions' => 'A short description of the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c8080a',
      'label' => 'Simulators',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c808aa',
      'label' => 'Homepage',
      'name' => 'transportationSimulator_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category simulators',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c80912',
      'label' => 'Heading Background',
      'name' => 'transportationSimulator_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category simulator headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c809b2',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'transportationSimulator_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80a50',
      'label' => 'Link List Background',
      'name' => 'transportationSimulator_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80ab7',
      'label' => 'Solutions',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c80b54',
      'label' => 'Homepage',
      'name' => 'transportationSolution_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category solutions',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c80bf5',
      'label' => 'Heading Background',
      'name' => 'transportationSolution_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category solution headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80c58',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'transportationSolution_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80d34',
      'label' => 'Link List Background',
      'name' => 'transportationSolution_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-transportation',
      ),
    ),
  ),
  'menu_order' => 34,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));




// Research options page
acf_add_local_field_group(array (
  'key' => 'group_58eb9e108d6da',
  'title' => 'Research',
  'fields' => array (
    array (
      'key' => 'field_58eb9e10ad426',
      'label' => 'General Settings',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e10ad486',
      'label' => 'Display Name',
      'name' => 'research_name',
      'type' => 'text',
      'instructions' => 'The name of the category as it appears throughout the site',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Military',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb9e10ad4d4',
      'label' => 'Category Icon',
      'name' => 'research_icon',
      'type' => 'image',
      'instructions' => 'The primary icon used to represent the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e10ad59c',
      'label' => 'Category Description',
      'name' => 'research_description',
      'type' => 'wysiwyg',
      'instructions' => 'A short description of the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58eb9e10ad661',
      'label' => 'Simulators',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e10ad6eb',
      'label' => 'Homepage',
      'name' => 'researchSimulator_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category simulators',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9e10ad799',
      'label' => 'Heading Background',
      'name' => 'researchSimulator_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category simulator headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e10ad84e',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'researchSimulator_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e10ad8d1',
      'label' => 'Link List Background',
      'name' => 'researchSimulator_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e10ad988',
      'label' => 'Solutions',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e10ada2f',
      'label' => 'Homepage',
      'name' => 'researchSolution_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category solutions',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9e10adad2',
      'label' => 'Heading Background',
      'name' => 'researchSolution_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category solution headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e10adb70',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'researchSolution_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e10adbd9',
      'label' => 'Link List Background',
      'name' => 'researchSolution_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-research',
      ),
    ),
  ),
  'menu_order' => 35,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>