<?php

acf_add_local_field_group(array (
  'key' => 'group_58e7e171e26b3',
  'title' => 'Theme Settings - Divisions',
  'fields' => array (
    array (
      'key' => 'field_58e7e2a190e98',
      'label' => 'FAAC Commercial',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58e7e3d252f75',
      'label' => 'Display Name',
      'name' => 'faacCommercial_name',
      'type' => 'text',
      'instructions' => 'The display name of the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'FAAC Commercial',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58e7e49252f79',
      'label' => 'Homepage',
      'name' => 'faacCommercial_homepage',
      'type' => 'url',
      'instructions' => 'The homepage of the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'https://faac.com/faac-commercial',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58e7e5b552f7d',
      'label' => 'Description',
      'name' => 'faacCommercial_description',
      'type' => 'wysiwyg',
      'instructions' => 'A short description of the division, used as a placeholder throughout the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo lacus sit amet sapien vestibulum eleifend. Duis sed semper sem. Proin quis volutpat odio. Nunc vel ligula quis justo volutpat condimentum suscipit in turpis. Aliquam ac lacus vel felis porttitor luctus. Fusce eget ipsum quis mauris euismod facilisis quis vel orci. Sed et nibh semper, consectetur lacus rhoncus, malesuada justo.',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58e7e7a5feced',
      'label' => 'Background Image',
      'name' => 'faacCommercial_background',
      'type' => 'image',
      'instructions' => 'Fallback image used for blocks that promote the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w480',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e842fecf1',
      'label' => 'Branding Logo',
      'name' => 'faacCommercial_logo',
      'type' => 'image',
      'instructions' => 'The primary logo used for the division throughout the website.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e947001ca',
      'label' => 'Menu Logo',
      'name' => 'faacCommercial_menuLogo',
      'type' => 'image',
      'instructions' => 'The logo used for the division in the main navigation menu. It may be the same or different than the branding logo.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e9c3001ce',
      'label' => 'Footer Logo',
      'name' => 'faacCommercial_footerLogo',
      'type' => 'image',
      'instructions' => 'The logo used for the division in the footer masthead. It may be the same or different than the branding and/or menu logos.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e2e190e99',
      'label' => 'FAAC Military',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58e7e40b52f76',
      'label' => 'Display Name',
      'name' => 'faacMilitary_name',
      'type' => 'text',
      'instructions' => 'The display name of the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'FAAC Military',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58e7e50052f7a',
      'label' => 'Homepage',
      'name' => 'faacMilitary_homepage',
      'type' => 'url',
      'instructions' => 'The homepage of the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'https://faac.com/faac-military',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58e7e69552f7e',
      'label' => 'Description',
      'name' => 'faacMilitary_description',
      'type' => 'wysiwyg',
      'instructions' => 'A short description of the division, used as a placeholder throughout the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo lacus sit amet sapien vestibulum eleifend. Duis sed semper sem. Proin quis volutpat odio. Nunc vel ligula quis justo volutpat condimentum suscipit in turpis. Aliquam ac lacus vel felis porttitor luctus. Fusce eget ipsum quis mauris euismod facilisis quis vel orci. Sed et nibh semper, consectetur lacus rhoncus, malesuada justo.',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58e7e7e9fecee',
      'label' => 'Background Image',
      'name' => 'faacMilitary_background',
      'type' => 'image',
      'instructions' => 'Fallback image used for blocks that promote the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w480',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e8e8fecf2',
      'label' => 'Branding Logo',
      'name' => 'faacMilitary_logo',
      'type' => 'image',
      'instructions' => 'The primary logo used for the division throughout the website.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e96f001cb',
      'label' => 'Menu Logo',
      'name' => 'faacMilitary_menuLogo',
      'type' => 'image',
      'instructions' => 'The logo used for the division in the main navigation menu. It may be the same or different than the branding logo.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e9eb001cf',
      'label' => 'Footer Logo',
      'name' => 'faacMilitary_footerLogo',
      'type' => 'image',
      'instructions' => 'The logo used for the division in the footer masthead. It may be the same or different than the branding and/or menu logos.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e2e790e9a',
      'label' => 'MILO Range',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58e7e41152f77',
      'label' => 'Display Name',
      'name' => 'miloRange_name',
      'type' => 'text',
      'instructions' => 'The display name of the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'MILO Range',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58e7e51552f7b',
      'label' => 'Homepage',
      'name' => 'miloRange_homepage',
      'type' => 'url',
      'instructions' => 'The homepage of the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'https://faac.com/milo-range',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58e7e6b152f7f',
      'label' => 'Description',
      'name' => 'miloRange_description',
      'type' => 'wysiwyg',
      'instructions' => 'A short description of the division, used as a placeholder throughout the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo lacus sit amet sapien vestibulum eleifend. Duis sed semper sem. Proin quis volutpat odio. Nunc vel ligula quis justo volutpat condimentum suscipit in turpis. Aliquam ac lacus vel felis porttitor luctus. Fusce eget ipsum quis mauris euismod facilisis quis vel orci. Sed et nibh semper, consectetur lacus rhoncus, malesuada justo.',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58e7e7fffecef',
      'label' => 'Background Image',
      'name' => 'miloRange_background',
      'type' => 'image',
      'instructions' => 'Fallback image used for blocks that promote the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w480',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e8fefecf3',
      'label' => 'Branding Logo',
      'name' => 'miloRange_logo',
      'type' => 'image',
      'instructions' => 'The primary logo used for the division throughout the website.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e985001cc',
      'label' => 'Menu Logo',
      'name' => 'miloRange_menuLogo',
      'type' => 'image',
      'instructions' => 'The logo used for the division in the main navigation menu. It may be the same or different than the branding logo.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7ea07001d0',
      'label' => 'Footer Logo',
      'name' => 'miloRange_footerLogo',
      'type' => 'image',
      'instructions' => 'The logo used for the division in the footer masthead. It may be the same or different than the branding and/or menu logos.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e2f190e9b',
      'label' => 'Realtime Technologies',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58e7e41852f78',
      'label' => 'Display Name',
      'name' => 'realtimeTechnologies_name',
      'type' => 'text',
      'instructions' => 'The display name of the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'RTI',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58e7e52552f7c',
      'label' => 'Homepage',
      'name' => 'realtimeTechnologies_homepage',
      'type' => 'url',
      'instructions' => 'The homepage of the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'https://faac.com/realtime-technologies',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58e7e6c852f80',
      'label' => 'Description',
      'name' => 'realtimeTechnologies_description',
      'type' => 'wysiwyg',
      'instructions' => 'A short description of the division, used as a placeholder throughout the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo lacus sit amet sapien vestibulum eleifend. Duis sed semper sem. Proin quis volutpat odio. Nunc vel ligula quis justo volutpat condimentum suscipit in turpis. Aliquam ac lacus vel felis porttitor luctus. Fusce eget ipsum quis mauris euismod facilisis quis vel orci. Sed et nibh semper, consectetur lacus rhoncus, malesuada justo.',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58e7e814fecf0',
      'label' => 'Background Image',
      'name' => 'realtimeTechnologies_background',
      'type' => 'image',
      'instructions' => 'Fallback image used for blocks that promote the division.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w480',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e90ffecf4',
      'label' => 'Branding Logo',
      'name' => 'realtimeTechnologies_logo',
      'type' => 'image',
      'instructions' => 'The primary logo used for the division throughout the website.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7e9a8001cd',
      'label' => 'Menu Logo',
      'name' => 'realtimeTechnologies_menuLogo',
      'type' => 'image',
      'instructions' => 'The logo used for the division in the main navigation menu. It may be the same or different than the branding logo.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7ea1a001d1',
      'label' => 'Footer Logo',
      'name' => 'realtimeTechnologies_footerLogo',
      'type' => 'image',
      'instructions' => 'The logo used for the division in the footer masthead. It may be the same or different than the branding and/or menu logos.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-divisions',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>