<?php

// Theme Defaults Page
acf_add_local_field_group(array (
  'key' => 'group_58ead2b37407f',
  'title' => 'Theme Defaults',
  'fields' => array (
    array (
      'key' => 'field_58ead2fdb3bc2',
      'label' => 'Brand Logo',
      'name' => 'theme_brandLogo',
      'type' => 'image',
      'instructions' => 'The logo associated with the brand as a whole.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58ead34d96bdd',
      'label' => 'Menu Logo',
      'name' => 'theme_menuLogo',
      'type' => 'image',
      'instructions' => 'The logo used in the primary navigation menu at the top of the page.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58ead39296bde',
      'label' => 'Footer Logo',
      'name' => 'theme_footerLogo',
      'type' => 'image',
      'instructions' => 'The logo used in the footer masthead.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-theme-defaults',
      ),
    ),
  ),
  'menu_order' => 10,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));




// Call to Action options page
acf_add_local_field_group(array (
  'key' => 'group_58eadccc1b1d2',
  'title' => 'Call to Action',
  'fields' => array (
    array (
      'key' => 'field_58eb8a8937378',
      'label' => 'Tagline',
      'name' => 'cta_tagline',
      'type' => 'text',
      'instructions' => 'The primary text that drives the call-to-action message',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Ready for High Fidelity Training?',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb8b7c37379',
      'label' => 'Button Text',
      'name' => 'cta_buttonText',
      'type' => 'text',
      'instructions' => 'The text on the cta button',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Speak to a Specialist',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb8ba73737a',
      'label' => 'Phone Number',
      'name' => 'cta_phoneNumber',
      'type' => 'text',
      'instructions' => 'The phone number to include as an alternate contact method.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => 'XXX-XXX-XXXX',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb8bdf3737b',
      'label' => 'Background Image',
      'name' => 'cta_background',
      'type' => 'image',
      'instructions' => 'The graphic to use as a graphic behind the cta content',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-calls-to-action',
      ),
    ),
  ),
  'menu_order' => 11,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));





// Photo Promotion options page
acf_add_local_field_group(array (
  'key' => 'group_58eadd23737f7',
  'title' => 'Photo Promotion',
  'fields' => array (
    array (
      'key' => 'field_58eb8cae7a84d',
      'label' => 'Headline',
      'name' => 'photoPromo_headline',
      'type' => 'text',
      'instructions' => 'The text displayed at the top of photo promotions',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb8d067a84e',
      'label' => 'Excerpt',
      'name' => 'photoPromo_excerpt',
      'type' => 'wysiwyg',
      'instructions' => 'The body text for the promotion',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58eb8d387a84f',
      'label' => 'Background Image',
      'name' => 'photoPromo_background',
      'type' => 'image',
      'instructions' => 'Background image used for the photo promotion',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb8d5c7a850',
      'label' => 'Linked Page',
      'name' => 'photoPromo_page',
      'type' => 'page_link',
      'instructions' => 'The page for the photo promo to link to',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-photo-promotions',
      ),
    ),
  ),
  'menu_order' => 12,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));




// Video Promotion options page
acf_add_local_field_group(array (
  'key' => 'group_58eb8db63711e',
  'title' => 'Theme Settings - Video Promotion',
  'fields' => array (
    array (
      'key' => 'field_58eb8db64b02c',
      'label' => 'Headline',
      'name' => 'videoPromo_headline',
      'type' => 'text',
      'instructions' => 'The text overlaid on top of video promotions',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb8db64b1f0',
      'label' => 'Linked Video',
      'name' => 'videoPromo_link',
      'type' => 'oembed',
      'instructions' => 'The source URL of the video',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'width' => '',
      'height' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-video-promotions',
      ),
    ),
  ),
  'menu_order' => 13,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));




// Footer Promotions options page
acf_add_local_field_group(array (
  'key' => 'group_58eade31389d4',
  'title' => 'Footer Promotions',
  'fields' => array (
    array (
      'key' => 'field_58eb8f860ae1f',
      'label' => 'Latest News',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb8ffd0ae22',
      'label' => 'Linked Page',
      'name' => 'news_link',
      'type' => 'page_link',
      'instructions' => 'The location of the page you\'d like to link to',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb903e0ae23',
      'label' => 'Short Description',
      'name' => 'news_description',
      'type' => 'text',
      'instructions' => 'A short sentence describing the link\'s purpose',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb93f20ae24',
      'label' => 'Background Image',
      'name' => 'news_image',
      'type' => 'image',
      'instructions' => 'The image to display behind the promotional link block',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb8ff00ae20',
      'label' => 'Resources',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb94840ae29',
      'label' => 'Linked Page',
      'name' => 'resources_link',
      'type' => 'page_link',
      'instructions' => 'The location of the page you\'d like to link to',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb94750ae27',
      'label' => 'Short Description',
      'name' => 'resources_description',
      'type' => 'text',
      'instructions' => 'A short sentence describing the link\'s purpose',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb946b0ae25',
      'label' => 'Background Image',
      'name' => 'resources_image',
      'type' => 'image',
      'instructions' => 'The image to display behind the promotional link block',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb8ff50ae21',
      'label' => 'Careers',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb94850ae2a',
      'label' => 'Linked Page',
      'name' => 'careers_link',
      'type' => 'page_link',
      'instructions' => 'The location of the page you\'d like to link to',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb94770ae28',
      'label' => 'Short Description',
      'name' => 'careers_description',
      'type' => 'text',
      'instructions' => 'A short sentence describing the link\'s purpose',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb946c0ae26',
      'label' => 'Background Image',
      'name' => 'careers_image',
      'type' => 'image',
      'instructions' => 'The image to display behind the promotional link block',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-footer-promotions',
      ),
    ),
  ),
  'menu_order' => 14,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>