<?php

acf_add_local_field_group(array (
  'key' => 'group_58d0223c875e6',
  'title' => 'Theme Settings - Features',
  'fields' => array (

    // Global Settings
    array (
      'key' => 'field_58e7b13526844',
      'label' => 'Global Settings',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58e7b862e8aa7',
      'label' => 'Brand Logo',
      'name' => 'global_brandLogo',
      'type' => 'image',
      'instructions' => 'The logo associated with the FAAC brand, for use throughout the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7b99de8aa8',
      'label' => 'Menu Logo',
      'name' => 'global_menuLogo',
      'type' => 'image',
      'instructions' => 'The logo, as it should appear in the primary navigation menu at the top of the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7ba31e8aa9',
      'label' => 'Footer Logo',
      'name' => 'global_footerLogo',
      'type' => 'image',
      'instructions' => 'The logo as it should appear in the page footer masthead.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),

    // Call to Action Defaults
    array (
      'key' => 'field_58d023c238525',
      'label' => 'Call to Action Defaults',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58d0491b4754d',
      'label' => 'Tagline',
      'name' => 'cta_tagline',
      'type' => 'text',
      'instructions' => 'For call-to-action blocks on the site, this is the text that promotes the intended action.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Ready for High Fidelity Training?',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58e7c0180894a',
      'label' => 'Button Text',
      'name' => 'cta_buttonText',
      'type' => 'text',
      'instructions' => 'For call-to-action blocks on the site, this is the text that promotes the intended action.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Speak to a Specialist',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d0498c4754e',
      'label' => 'Phone Number',
      'name' => 'cta_phoneNumber',
      'type' => 'text',
      'instructions' => 'The number use to phone links in call-to-action blocks
(Please use XXX-XXX-XXXX as the format)',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '800-555-5555',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d049c34754f',
      'label' => 'Background Photo',
      'name' => 'cta_backgroundPhoto',
      'type' => 'image',
      'instructions' => 'Background imagery for call-to-action blocks.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),

    // Photo Promotion Defaults
    array (
      'key' => 'field_58d0236f38523',
      'label' => 'Photo Promotion Defaults',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58d046a8f864a',
      'label' => 'Headline',
      'name' => 'photoPromo_headline',
      'type' => 'text',
      'instructions' => 'The headline text for photo-driven promotional areas throughout the site.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'FAAC Promotional Area',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d046d9f864b',
      'label' => 'Excerpt',
      'name' => 'photoPromo_excerpt',
      'type' => 'wysiwyg',
      'instructions' => 'Body text for photo promotions.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo lacus sit amet sapien vestibulum eleifend. Duis sed semper sem. Proin quis volutpat odio. Nunc vel ligula quis justo volutpat condimentum suscipit in turpis. Aliquam ac lacus vel felis porttitor luctus. Fusce eget ipsum quis mauris euismod facilisis quis vel orci. Sed et nibh semper, consectetur lacus rhoncus, malesuada justo. Praesent augue eros, varius ut metus volutpat, volutpat scelerisque eros. Aliquam nunc sem, dictum nec pellentesque at, aliquam id mauris. Phasellus sed euismod ipsum. Proin at nisi varius orci semper tristique elementum egestas quam. Proin eget gravida dolor.

Aliquam tempor id elit maximus dignissim. Cras varius bibendum lacinia.',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58d04754f864c',
      'label' => 'Background Photo',
      'name' => 'photoPromo_backgroundPhoto',
      'type' => 'image',
      'instructions' => 'The image to use for photo promotions - this may be a picture of a simulator, an event, etc. and is displayed behind and to the side of the text.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7c571e0f4d',
      'label' => 'Linked Page',
      'name' => 'photoPromo_pageLink',
      'type' => 'url',
      'instructions' => 'The page to which the promotion will link. This may exist within the FAAC site or outside of it.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
    ),

    // Video Promotion Defaults
    array (
      'key' => 'field_58d0233238521',
      'label' => 'Video Promotion Defaults',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58d043dce484c',
      'label' => 'Headline',
      'name' => 'videoPromo_headline',
      'type' => 'text',
      'instructions' => 'The headline text for video-driven promotional areas throughout the site. This appears on top of the video player.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem ipsum dolor sit amet, consectetur',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d0449ce484d',
      'label' => 'Video URL',
      'name' => 'videoPromo_URL',
      'type' => 'url',
      'instructions' => 'The location of the video to be displayed.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
    ),

    // Footer Link Defaults
    array (
      'key' => 'field_58d023c838526',
      'label' => 'Footer Link Defaults',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58e7c6cec1050',
      'label' => 'Latest News Description',
      'name' => 'latestNews_description',
      'type' => 'text',
      'instructions' => 'The text displayed below the title for "Latest News" cards below the main content.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d04d79c9eba',
      'label' => 'Latest News Page',
      'name' => 'latestNews_page',
      'type' => 'page_link',
      'instructions' => 'The page where the latest news is displayed. Likely to be a post archive page.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'page',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58e7caa2c1054',
      'label' => 'Latest News Background Photo',
      'name' => 'latestNews_backgroundPhoto',
      'type' => 'image',
      'instructions' => 'The photo to appear on "Latest News" cards below the content.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7c83dc1051',
      'label' => 'Resources Description',
      'name' => 'resources_description',
      'type' => 'text',
      'instructions' => 'The text displayed below the title for "Resources" cards below the main content.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d04ea1ad068',
      'label' => 'Resources Page',
      'name' => 'resources_page',
      'type' => 'page_link',
      'instructions' => 'The page where site resources displayed. Likely to be a post archive page.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'page',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58e7cd72c1057',
      'label' => 'Resources Background Photo',
      'name' => 'resources_backgroundPhoto',
      'type' => 'image',
      'instructions' => 'The photo to appear on "Resources" cards below the content.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58e7c856c1052',
      'label' => 'Careers Description',
      'name' => 'careers_description',
      'type' => 'text',
      'instructions' => 'The text displayed below the title for "Careers" cards below the main content.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58d04eb4ad069',
      'label' => 'Careers Page',
      'name' => 'careers_page',
      'type' => 'page_link',
      'instructions' => 'The page where site resources displayed. Likely to be a post archive page.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'page',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58e7ced4c105a',
      'label' => 'Careers Background Photo',
      'name' => 'careers_backgroundPhoto',
      'type' => 'image',
      'instructions' => 'The photo to appear on "Careers" cards below the content.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),


  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-features',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>