<?php

acf_add_local_field_group(array (
  'key' => 'group_58eb9e0c6cc7d',
  'title' => 'Categories - Transportation',
  'fields' => array (
    array (
      'key' => 'field_58eb9e0c806f7',
      'label' => 'General Settings',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c80735',
      'label' => 'Display Name',
      'name' => 'transportation_name',
      'type' => 'text',
      'instructions' => 'The name of the category as it appears throughout the site',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Military',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80768',
      'label' => 'Category Icon',
      'name' => 'transportation_icon',
      'type' => 'image',
      'instructions' => 'The primary icon used to represent the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w160',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80799',
      'label' => 'Category Description',
      'name' => 'transportation_description',
      'type' => 'wysiwyg',
      'instructions' => 'A short description of the category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c8080a',
      'label' => 'Simulators',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c808aa',
      'label' => 'Homepage',
      'name' => 'transportationSimulator_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category simulators',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c80912',
      'label' => 'Heading Background',
      'name' => 'transportationSimulator_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category simulator headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c809b2',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'transportationSimulator_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80a50',
      'label' => 'Link List Background',
      'name' => 'transportationSimulator_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80ab7',
      'label' => 'Solutions',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c80b54',
      'label' => 'Homepage',
      'name' => 'transportationSolution_homepage',
      'type' => 'page_link',
      'instructions' => 'The homepage for category solutions',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'allow_archives' => 1,
      'multiple' => 0,
    ),
    array (
      'key' => 'field_58eb9e0c80bf5',
      'label' => 'Heading Background',
      'name' => 'transportationSolution_headingBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for category solution headings',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80c58',
      'label' => 'Featured Simulator / Promotion Background',
      'name' => 'transportationSolution_promoBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58eb9e0c80d34',
      'label' => 'Link List Background',
      'name' => 'transportationSolution_listBackground',
      'type' => 'image',
      'instructions' => 'Background image to use for features and promotions related to this category',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'w360',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-transportation',
      ),
    ),
  ),
  'menu_order' => 34,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>