<?php

acf_add_local_field_group(array (
  'key' => 'group_58d3f05fbacaf',
  'title' => '110 - Dynamic Slider',
  'fields' => array (
    array (
      'key' => 'field_58d3f05fbf1cf',
      'label' => 'Dynamic Slider',
      'name' => 'dynamicSlider',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '100',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Add Slide',
      'sub_fields' => array (
        array (
          'key' => 'field_58d3f12231cab',
          'label' => 'Slide Image',
          'name' => 'slider_image',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '100',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'w360',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array (
          'key' => 'field_58d3f16331cac',
          'label' => 'Upper Text',
          'name' => 'slider_upperText',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_58d3f18531cad',
          'label' => 'Lower Text',
          'name' => 'slider_lowerText',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_590c957d2a7dc',
          'label' => 'Slide Link',
          'name' => 'slider_slideLink',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'message' => 'Should this slide be linked?',
          'default_value' => 0,
          'ui' => 0,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
        array (
          'key' => 'field_590c95ec2a7dd',
          'label' => 'Link URL',
          'name' => 'slider_linkURL',
          'type' => 'url',
          'instructions' => 'The URL (webpage, video, etc.) to link to',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_590c957d2a7dc',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
        ),
        array (
          'key' => 'field_590c962a2a7de',
          'label' => 'Link Text',
          'name' => 'slider_linkText',
          'type' => 'text',
          'instructions' => 'The text to link with the URL',
          'required' => 0,
          'conditional_logic' => array (
            array (
              array (
                'field' => 'field_590c957d2a7dc',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 'Learn More >>',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'acf_after_title',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
  ),
  'active' => 0,
  'description' => '',
));

?>