<?php

acf_add_local_field_group(array (
  'key' => 'group_58f3947fe397c',
  'title' => 'Widget - Copyright Info',
  'fields' => array (
    array (
      'key' => 'field_58f394a81b45b',
      'label' => 'Company Name',
      'name' => 'copyright_name',
      'type' => 'text',
      'instructions' => 'The name of the company to whom the copyright applies. All other info is added automatically.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'FAAC Incorporated',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58f395241b45c',
      'label' => 'Sitemap Link',
      'name' => 'copyright_sitemap',
      'type' => 'url',
      'instructions' => 'The URL of the website sitemap',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58f395841b45d',
      'label' => 'Privacy Policy Link',
      'name' => 'copyright_privacyPolicy',
      'type' => 'url',
      'instructions' => 'The URL of the website\'s Privacy Policy',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58f395a41b45e',
      'label' => 'Terms of Service Link',
      'name' => 'copyright_termsOfService',
      'type' => 'url',
      'instructions' => 'The URL of the website\'s Terms of Service',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58f3960a1b45f',
      'label' => 'Design Credit',
      'name' => 'copyright_designCredit',
      'type' => 'text',
      'instructions' => 'The HTML string to use for the site\'s design crediting.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Web Design by <a href="http://www.designfwd.com/">FWD</a>',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'widget',
        'operator' => '==',
        'value' => 'acf_widget_1754',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

?>